// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MiniClone",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "MiniClone",
            targets: ["App"],
            bundleIdentifier: "com.tsaiton.MiniClone",
            teamIdentifier: "4H38Q8RQV5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown
            ],
            capabilities: [
                .photoLibrary(purposeString: "We need access to your photos to insert them into your notes."),
                .camera(purposeString: "We need access to your camera to take photos and insert them into your notes.")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/google/generative-ai-swift", "0.5.6"..<"1.0.0"),
        .package(url: "https://github.com/colinc86/MathJaxSwift", "3.4.0"..<"4.0.0"),
        .package(url: "https://github.com/colinc86/LaTeXSwiftUI", .branch("main")),
        .package(url: "https://github.com/swhitty/SwiftDraw", "0.25.3"..<"1.0.0"),
        .package(url: "https://github.com/Kitura/swift-html-entities", "4.0.1"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                .product(name: "GoogleGenerativeAI", package: "generative-ai-swift"),
                .product(name: "MathJaxSwift", package: "MathJaxSwift"),
                .product(name: "LaTeXSwiftUI", package: "LaTeXSwiftUI"),
                .product(name: "SwiftDraw", package: "SwiftDraw"),
                .product(name: "HTMLEntities", package: "swift-html-entities")
            ],
            path: "Sources"
        )
    ]
)